# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-25 14:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShortUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long_url', models.CharField(max_length=2500)),
                ('short_url', models.CharField(max_length=32, unique=True)),
                ('last_checked', models.DateTimeField(auto_now_add=True)),
                ('no_of_views', models.PositiveIntegerField(default=0)),
                ('redirect_location', models.CharField(default='', max_length=2500)),
            ],
            options={
                'ordering': ['-pk'],
            },
        ),
    ]
